### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chetan1836** [anmolpanwar/E-voting-system-on-blockchain#3]
When I try to vote I get the following error.

[2020-08-04 17:22:44,758] ERROR in app: Exception on /vote [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Projects/Myproject/Python/E-voting-system-on-blockchain/Major2/blockchain.py", line 334, in voter
    encvotedata = v1.encryptvote()
  File "C:/Projects/Myproject/Python/E-voting-system-on-blockchain/Major2/blockchain.py", line 56, in encryptvote
    self.votedata.append(enc.sign(voterkeys['sk'], bytes(sha256(str('---'.join(str(x) for x in self.votedata)).encode('utf-8')).hexdigest(),'utf-8')))
  File "C:\Projects\Myproject\Python\E-voting-system-on-blockchain\Major2\enc.py", line 32, in sign
    return base64.b64encode(str((privatekey.sign(data,''))[0]).encode())
  File "C:\ProgramData\Anaconda3\envs\E-voting-system-on-blockchain\lib\site-packages\Crypto\PublicKey\RSA.py", line 384, in sign
    raise NotImplementedError("Use module Crypto.Signature.pkcs1_15 instead")
NotImplementedError: Use module Crypto.Signature.pkcs1_15 instead

Please give me a solution.

**Comment by anmolpanwar** [comment]
Alright the `sign` function in the file `enc.py` is giving out some error.
May I ask which IDE are you using?? 
If you are using Pycharm, please navigate to the `venv>lib>python3.x>site-packages` folder of your project in the terminal/command prompt and send me the names of folders in the above mention directory.

**Comment by chetan1836** [comment]
I'm using Pycryptodome library. Is that why I'm getting error.

**Comment by anmolpanwar** [comment]
Yeah maybe. I cannot say for sure. But Pycryptodome didn't work out well for me so I used `Cryptography`, `pycrypto` and `crypto`

**Comment by anmolpanwar** [comment]
Also, there is an issue with `Crypto` when you install it. Thus, then when importing, it will give out an error, unless they updated the version and fixed the issue. But you need to install it because most of the cryptographic part of the code (like the `enc.py` file and others) use **Crypto** library. 
If you encounter the same issue that I faced, I’ll help you out. Otherwise, you’re good to go.
If you still face any issues, feel free to contact :)

**Comment by chetan1836** [comment]
I having trouble installing `Pycrypto` in `python 3.7` running `windows 10`. So, I installed `Pycryptodome` which is a fork of `Pycrypto`. But, Pycryptodome doesn't support these functions:

## Methods defined in PyCrypto that doesn't support anymore
    def sign(self, M, K):
        raise NotImplementedError("Use module Crypto.Signature.pkcs1_15 instead")

    def verify(self, M, signature):
        raise NotImplementedError("Use module Crypto.Signature.pkcs1_15 instead")

    def encrypt(self, plaintext, K):
        raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")

    def decrypt(self, ciphertext):
        raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")

Do you have a Pycrypto wheel file that I can use.

**Comment by anmolpanwar** [comment]
Alright. I am sharing the Crypto module folder. Unzip the file and place the folder in the `venv/lib/pythonX.X/site-packages` folder. You’ll find this **venv** folder where you’ve created your python project.
[Crypto.zip](https://github.com/anmolpanwar/E-voting-system-on-blockchain/files/5028744/Crypto.zip)

**Comment by anmolpanwar** [comment]
Is your code working now? May I close this thread?

**Comment by chetan1836** [comment]
Thanks for the help.
